import type { ThemeConfig } from '../types';

export type ThemeKey = 'white-blue' | 'white-green' | 'white-pink' | 'black-pink';

export const THEMES: Record<string, ThemeConfig> = {
  'white-blue': {
    name: 'White & Blue', bg: 'bg-white', textMain: 'text-slate-900', textMuted: 'text-slate-500', textSub: 'text-slate-400', textSubHover: 'hover:text-slate-600', placeholder: 'placeholder:text-slate-400', border: 'border-slate-200', surface: 'bg-slate-50', surfaceHover: 'hover:bg-slate-100', surfaceBorder: 'border-slate-100', primary: 'bg-blue-500 hover:bg-blue-600 text-white', primaryText: 'text-blue-500', primarySoft: 'bg-blue-50', primarySoftText: 'text-blue-600', primaryBorder: 'border-blue-500', primarySoftBorder: 'border-blue-100', primaryRing: 'focus-within:border-blue-400 focus-within:ring-blue-50', primaryActiveOp: 'bg-blue-100 border border-blue-200 text-blue-600', toggleActive: 'bg-blue-500', keypadContainer: 'bg-white border-slate-100 shadow-[0_-15px_40px_-15px_rgba(0,0,0,0.08)]', btnNum: 'bg-white hover:bg-slate-50 text-slate-800 border border-slate-200/60', btnSpecial: 'bg-slate-50/50 hover:bg-slate-100 text-slate-600 border border-slate-100', inputCard: 'bg-white border-slate-200', modalBg: 'bg-white border-slate-200 shadow-xl', modalOverlay: 'bg-slate-900/20', successBg: 'bg-emerald-100', successIcon: 'text-emerald-500',
  },
  'white-green': {
    name: 'White & Green', bg: 'bg-white', textMain: 'text-slate-900', textMuted: 'text-slate-500', textSub: 'text-slate-400', textSubHover: 'hover:text-slate-600', placeholder: 'placeholder:text-slate-400', border: 'border-slate-200', surface: 'bg-slate-50', surfaceHover: 'hover:bg-slate-100', surfaceBorder: 'border-slate-100', primary: 'bg-emerald-500 hover:bg-emerald-600 text-white', primaryText: 'text-emerald-500', primarySoft: 'bg-emerald-50', primarySoftText: 'text-emerald-600', primaryBorder: 'border-emerald-500', primarySoftBorder: 'border-emerald-100', primaryRing: 'focus-within:border-emerald-400 focus-within:ring-emerald-50', primaryActiveOp: 'bg-emerald-100 border border-emerald-200 text-emerald-600', toggleActive: 'bg-emerald-500', keypadContainer: 'bg-white border-slate-100 shadow-[0_-15px_40px_-15px_rgba(0,0,0,0.08)]', btnNum: 'bg-white hover:bg-slate-50 text-slate-800 border border-slate-200/60', btnSpecial: 'bg-slate-50/50 hover:bg-slate-100 text-slate-600 border border-slate-100', inputCard: 'bg-white border-slate-200', modalBg: 'bg-white border-slate-200 shadow-xl', modalOverlay: 'bg-slate-900/20', successBg: 'bg-emerald-100', successIcon: 'text-emerald-500',
  },
  'white-pink': {
    name: 'White & Pink', bg: 'bg-white', textMain: 'text-slate-900', textMuted: 'text-slate-500', textSub: 'text-slate-400', textSubHover: 'hover:text-slate-600', placeholder: 'placeholder:text-slate-400', border: 'border-slate-200', surface: 'bg-slate-50', surfaceHover: 'hover:bg-slate-100', surfaceBorder: 'border-slate-100', primary: 'bg-pink-500 hover:bg-pink-600 text-white', primaryText: 'text-pink-500', primarySoft: 'bg-pink-50', primarySoftText: 'text-pink-600', primaryBorder: 'border-pink-500', primarySoftBorder: 'border-pink-100', primaryRing: 'focus-within:border-pink-400 focus-within:ring-pink-50', primaryActiveOp: 'bg-pink-100 border border-pink-200 text-pink-600', toggleActive: 'bg-pink-500', keypadContainer: 'bg-white border-slate-100 shadow-[0_-15px_40px_-15px_rgba(0,0,0,0.08)]', btnNum: 'bg-white hover:bg-slate-50 text-slate-800 border border-slate-200/60', btnSpecial: 'bg-slate-50/50 hover:bg-slate-100 text-slate-600 border border-slate-100', inputCard: 'bg-white border-slate-200', modalBg: 'bg-white border-slate-200 shadow-xl', modalOverlay: 'bg-slate-900/20', successBg: 'bg-emerald-100', successIcon: 'text-emerald-500',
  },
  'black-pink': {
    name: 'Black & Pink', bg: 'bg-slate-950', textMain: 'text-slate-100', textMuted: 'text-slate-400', textSub: 'text-slate-500', textSubHover: 'hover:text-slate-300', placeholder: 'placeholder:text-slate-500', border: 'border-slate-800', surface: 'bg-slate-900', surfaceHover: 'hover:bg-slate-800', surfaceBorder: 'border-slate-800', primary: 'bg-pink-600 hover:bg-pink-700 text-white', primaryText: 'text-pink-500', primarySoft: 'bg-pink-500/10', primarySoftText: 'text-pink-400', primaryBorder: 'border-pink-500', primarySoftBorder: 'border-pink-500/20', primaryRing: 'focus-within:border-pink-500/50 focus-within:ring-pink-500/20', primaryActiveOp: 'bg-pink-500/20 border border-pink-500/30 text-pink-400', toggleActive: 'bg-pink-600', keypadContainer: 'bg-slate-900 border-slate-800 border-t shadow-[0_-15px_40px_-15px_rgba(0,0,0,0.5)]', btnNum: 'bg-slate-950 hover:bg-slate-800 text-slate-100 border border-slate-800', btnSpecial: 'bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700', inputCard: 'bg-slate-950 border-slate-800', modalBg: 'bg-slate-900 border-slate-800 shadow-2xl', modalOverlay: 'bg-black/60', successBg: 'bg-emerald-500/20', successIcon: 'text-emerald-400',
  },
};

export const DEFAULT_THEME: ThemeKey = 'white-blue';
